### ISSUE TITLE
Question on paper figure

### ISSUE THREAD

**Issue by bowen118** [aetherAI/hms2#1]
Very nice paper! We are thinking of using your repo for a project, but we are trying to figure out how much computational resources we should plan for and have some questions on the throughput. In [figure 3](https://www.nature.com/articles/s41467-022-30746-1/figures/3) of your paper, were these measurements collected on a single GPU or multiple? 

Thanks

**Comment by chenchc** [comment]
Hi @bowen118,

The throughputs shown in Figure 3 were measured on a single V100 GPU. Basically, you can estimate the throughput of a multi-GPU environment by (#GPUs) * (single-GPU throughput) * (scaling efficiency, say 0.9). 

Good luck with your project!

**Comment by bowen118** [comment]
Thanks!
